apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-fixed-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-fixed-app
  template:
    metadata:
      labels:
        app: java-fixed-app
    spec:
      containers:
      - name: java-fixed
        image: grivvus/java_fixed:latest
        ports:
          - containerPort: 8080
