apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-fixed-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Grivvus/java_kuber.git
    path: .
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      # parameters:
      #   - name: service.nodePort
      #     value: "30000"
      #   - name: image.tag
      #     value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
