apiVersion: v1
kind: Service
metadata:
  name: java-fixed-service
spec:
  type: NodePort
  selector:
    app: java-fixed-app
  ports:
    - protocol: TCP
      port: 8080          # Service port
      targetPort: 8080     # Pod port
      nodePort: 30000
