apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-fixed.fullname" .}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "java-fixed.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "java-fixed.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.service.targetPort }}
