apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-fixed.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{- include "java-fixed.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
